[package]
name = "tails"
description = "Tails Scripting Language WebAssembly Module"
version = "0.2.0"
authors = ["Tom McIntosh"]
license = "MIT"
repository = "https://github.com/tj-mc/tails"

[package.metadata.wasm-pack.profile.release]
wee_alloc = false